#pragma once

#include "maths.vector.h"

#define MATHS_SHIFT_LABEL_0 x, r
#define MATHS_SHIFT_LABEL_1 y, g
#define MATHS_SHIFT_LABEL_2 z, b
#define MATHS_SHIFT_LABEL_3 w, a

#define MATHS_SHIFT_LABEL_00 xx, rr
#define MATHS_SHIFT_LABEL_01 xy, rg
#define MATHS_SHIFT_LABEL_02 xz, rb
#define MATHS_SHIFT_LABEL_03 xw, ra
#define MATHS_SHIFT_LABEL_10 yx, gr
#define MATHS_SHIFT_LABEL_11 yy, gg
#define MATHS_SHIFT_LABEL_12 yz, gb
#define MATHS_SHIFT_LABEL_13 yw, ga
#define MATHS_SHIFT_LABEL_20 zx, br
#define MATHS_SHIFT_LABEL_21 zy, bg
#define MATHS_SHIFT_LABEL_22 zz, bb
#define MATHS_SHIFT_LABEL_23 zw, ba
#define MATHS_SHIFT_LABEL_30 wx, ar
#define MATHS_SHIFT_LABEL_31 wy, ag
#define MATHS_SHIFT_LABEL_32 wz, ab
#define MATHS_SHIFT_LABEL_33 ww, aa

#define MATHS_SHIFT_LABEL_000 xxx, rrr
#define MATHS_SHIFT_LABEL_001 xxy, rrg
#define MATHS_SHIFT_LABEL_002 xxz, rrb
#define MATHS_SHIFT_LABEL_003 xxw, rra
#define MATHS_SHIFT_LABEL_010 xyx, rgr
#define MATHS_SHIFT_LABEL_011 xyy, rgg
#define MATHS_SHIFT_LABEL_012 xyz, rgb
#define MATHS_SHIFT_LABEL_013 xyw, rga
#define MATHS_SHIFT_LABEL_020 xzx, rbr
#define MATHS_SHIFT_LABEL_021 xzy, rbg
#define MATHS_SHIFT_LABEL_022 xzz, rbb
#define MATHS_SHIFT_LABEL_023 xzw, rba
#define MATHS_SHIFT_LABEL_030 xwx, rar
#define MATHS_SHIFT_LABEL_031 xwy, rag
#define MATHS_SHIFT_LABEL_032 xwz, rab
#define MATHS_SHIFT_LABEL_033 xww, raa
#define MATHS_SHIFT_LABEL_100 yxx, grr
#define MATHS_SHIFT_LABEL_101 yxy, grg
#define MATHS_SHIFT_LABEL_102 yxz, grb
#define MATHS_SHIFT_LABEL_103 yxw, gra
#define MATHS_SHIFT_LABEL_110 yyx, ggr
#define MATHS_SHIFT_LABEL_111 yyy, ggg
#define MATHS_SHIFT_LABEL_112 yyz, ggb
#define MATHS_SHIFT_LABEL_113 yyw, gga
#define MATHS_SHIFT_LABEL_120 yzx, gbr
#define MATHS_SHIFT_LABEL_121 yzy, gbg
#define MATHS_SHIFT_LABEL_122 yzz, gbb
#define MATHS_SHIFT_LABEL_123 yzw, gba
#define MATHS_SHIFT_LABEL_130 ywx, gar
#define MATHS_SHIFT_LABEL_131 ywy, gag
#define MATHS_SHIFT_LABEL_132 ywz, gab
#define MATHS_SHIFT_LABEL_133 yww, gaa
#define MATHS_SHIFT_LABEL_200 zxx, brr
#define MATHS_SHIFT_LABEL_201 zxy, brg
#define MATHS_SHIFT_LABEL_202 zxz, brb
#define MATHS_SHIFT_LABEL_203 zxw, bra
#define MATHS_SHIFT_LABEL_210 zyx, bgr
#define MATHS_SHIFT_LABEL_211 zyy, bgg
#define MATHS_SHIFT_LABEL_212 zyz, bgb
#define MATHS_SHIFT_LABEL_213 zyw, bga
#define MATHS_SHIFT_LABEL_220 zzx, bbr
#define MATHS_SHIFT_LABEL_221 zzy, bbg
#define MATHS_SHIFT_LABEL_222 zzz, bbb
#define MATHS_SHIFT_LABEL_223 zzw, bba
#define MATHS_SHIFT_LABEL_230 zwx, bar
#define MATHS_SHIFT_LABEL_231 zwy, bag
#define MATHS_SHIFT_LABEL_232 zwz, bab
#define MATHS_SHIFT_LABEL_233 zww, baa
#define MATHS_SHIFT_LABEL_300 wxx, arr
#define MATHS_SHIFT_LABEL_301 wxy, arg
#define MATHS_SHIFT_LABEL_302 wxz, arb
#define MATHS_SHIFT_LABEL_303 wxw, ara
#define MATHS_SHIFT_LABEL_310 wyx, agr
#define MATHS_SHIFT_LABEL_311 wyy, agg
#define MATHS_SHIFT_LABEL_312 wyz, agb
#define MATHS_SHIFT_LABEL_313 wyw, aga
#define MATHS_SHIFT_LABEL_320 wzx, abr
#define MATHS_SHIFT_LABEL_321 wzy, abg
#define MATHS_SHIFT_LABEL_322 wzz, abb
#define MATHS_SHIFT_LABEL_323 wzw, aba
#define MATHS_SHIFT_LABEL_330 wwx, aar
#define MATHS_SHIFT_LABEL_331 wwy, aag
#define MATHS_SHIFT_LABEL_332 wwz, aab
#define MATHS_SHIFT_LABEL_333 www, aaa

#define MATHS_SHIFT_LABEL_0000 xxxx, rrrr
#define MATHS_SHIFT_LABEL_0001 xxxy, rrrg
#define MATHS_SHIFT_LABEL_0002 xxxz, rrrb
#define MATHS_SHIFT_LABEL_0003 xxxw, rrra
#define MATHS_SHIFT_LABEL_0010 xxyx, rrgr
#define MATHS_SHIFT_LABEL_0011 xxyy, rrgg
#define MATHS_SHIFT_LABEL_0012 xxyz, rrgb
#define MATHS_SHIFT_LABEL_0013 xxyw, rrga
#define MATHS_SHIFT_LABEL_0020 xxzx, rrbr
#define MATHS_SHIFT_LABEL_0021 xxzy, rrbg
#define MATHS_SHIFT_LABEL_0022 xxzz, rrbb
#define MATHS_SHIFT_LABEL_0023 xxzw, rrba
#define MATHS_SHIFT_LABEL_0030 xxwx, rrar
#define MATHS_SHIFT_LABEL_0031 xxwy, rrag
#define MATHS_SHIFT_LABEL_0032 xxwz, rrab
#define MATHS_SHIFT_LABEL_0033 xxww, rraa
#define MATHS_SHIFT_LABEL_0100 xyxx, rgrr
#define MATHS_SHIFT_LABEL_0101 xyxy, rgrg
#define MATHS_SHIFT_LABEL_0102 xyxz, rgrb
#define MATHS_SHIFT_LABEL_0103 xyxw, rgra
#define MATHS_SHIFT_LABEL_0110 xyyx, rggr
#define MATHS_SHIFT_LABEL_0111 xyyy, rggg
#define MATHS_SHIFT_LABEL_0112 xyyz, rggb
#define MATHS_SHIFT_LABEL_0113 xyyw, rgga
#define MATHS_SHIFT_LABEL_0120 xyzx, rgbr
#define MATHS_SHIFT_LABEL_0121 xyzy, rgbg
#define MATHS_SHIFT_LABEL_0122 xyzz, rgbb
#define MATHS_SHIFT_LABEL_0123 xyzw, rgba
#define MATHS_SHIFT_LABEL_0130 xywx, rgar
#define MATHS_SHIFT_LABEL_0131 xywy, rgag
#define MATHS_SHIFT_LABEL_0132 xywz, rgab
#define MATHS_SHIFT_LABEL_0133 xyww, rgaa
#define MATHS_SHIFT_LABEL_0200 xzxx, rbrr
#define MATHS_SHIFT_LABEL_0201 xzxy, rbrg
#define MATHS_SHIFT_LABEL_0202 xzxz, rbrb
#define MATHS_SHIFT_LABEL_0203 xzxw, rbra
#define MATHS_SHIFT_LABEL_0210 xzyx, rbgr
#define MATHS_SHIFT_LABEL_0211 xzyy, rbgg
#define MATHS_SHIFT_LABEL_0212 xzyz, rbgb
#define MATHS_SHIFT_LABEL_0213 xzyw, rbga
#define MATHS_SHIFT_LABEL_0220 xzzx, rbbr
#define MATHS_SHIFT_LABEL_0221 xzzy, rbbg
#define MATHS_SHIFT_LABEL_0222 xzzz, rbbb
#define MATHS_SHIFT_LABEL_0223 xzzw, rbba
#define MATHS_SHIFT_LABEL_0230 xzwx, rbar
#define MATHS_SHIFT_LABEL_0231 xzwy, rbag
#define MATHS_SHIFT_LABEL_0232 xzwz, rbab
#define MATHS_SHIFT_LABEL_0233 xzww, rbaa
#define MATHS_SHIFT_LABEL_0300 xwxx, rarr
#define MATHS_SHIFT_LABEL_0301 xwxy, rarg
#define MATHS_SHIFT_LABEL_0302 xwxz, rarb
#define MATHS_SHIFT_LABEL_0303 xwxw, rara
#define MATHS_SHIFT_LABEL_0310 xwyx, ragr
#define MATHS_SHIFT_LABEL_0311 xwyy, ragg
#define MATHS_SHIFT_LABEL_0312 xwyz, ragb
#define MATHS_SHIFT_LABEL_0313 xwyw, raga
#define MATHS_SHIFT_LABEL_0320 xwzx, rabr
#define MATHS_SHIFT_LABEL_0321 xwzy, rabg
#define MATHS_SHIFT_LABEL_0322 xwzz, rabb
#define MATHS_SHIFT_LABEL_0323 xwzw, raba
#define MATHS_SHIFT_LABEL_0330 xwwx, raar
#define MATHS_SHIFT_LABEL_0331 xwwy, raag
#define MATHS_SHIFT_LABEL_0332 xwwz, raab
#define MATHS_SHIFT_LABEL_0333 xwww, raaa
#define MATHS_SHIFT_LABEL_1000 yxxx, grrr
#define MATHS_SHIFT_LABEL_1001 yxxy, grrg
#define MATHS_SHIFT_LABEL_1002 yxxz, grrb
#define MATHS_SHIFT_LABEL_1003 yxxw, grra
#define MATHS_SHIFT_LABEL_1010 yxyx, grgr
#define MATHS_SHIFT_LABEL_1011 yxyy, grgg
#define MATHS_SHIFT_LABEL_1012 yxyz, grgb
#define MATHS_SHIFT_LABEL_1013 yxyw, grga
#define MATHS_SHIFT_LABEL_1020 yxzx, grbr
#define MATHS_SHIFT_LABEL_1021 yxzy, grbg
#define MATHS_SHIFT_LABEL_1022 yxzz, grbb
#define MATHS_SHIFT_LABEL_1023 yxzw, grba
#define MATHS_SHIFT_LABEL_1030 yxwx, grar
#define MATHS_SHIFT_LABEL_1031 yxwy, grag
#define MATHS_SHIFT_LABEL_1032 yxwz, grab
#define MATHS_SHIFT_LABEL_1033 yxww, graa
#define MATHS_SHIFT_LABEL_1100 yyxx, ggrr
#define MATHS_SHIFT_LABEL_1101 yyxy, ggrg
#define MATHS_SHIFT_LABEL_1102 yyxz, ggrb
#define MATHS_SHIFT_LABEL_1103 yyxw, ggra
#define MATHS_SHIFT_LABEL_1110 yyyx, gggr
#define MATHS_SHIFT_LABEL_1111 yyyy, gggg
#define MATHS_SHIFT_LABEL_1112 yyyz, gggb
#define MATHS_SHIFT_LABEL_1113 yyyw, ggga
#define MATHS_SHIFT_LABEL_1120 yyzx, ggbr
#define MATHS_SHIFT_LABEL_1121 yyzy, ggbg
#define MATHS_SHIFT_LABEL_1122 yyzz, ggbb
#define MATHS_SHIFT_LABEL_1123 yyzw, ggba
#define MATHS_SHIFT_LABEL_1130 yywx, ggar
#define MATHS_SHIFT_LABEL_1131 yywy, ggag
#define MATHS_SHIFT_LABEL_1132 yywz, ggab
#define MATHS_SHIFT_LABEL_1133 yyww, ggaa
#define MATHS_SHIFT_LABEL_1200 yzxx, gbrr
#define MATHS_SHIFT_LABEL_1201 yzxy, gbrg
#define MATHS_SHIFT_LABEL_1202 yzxz, gbrb
#define MATHS_SHIFT_LABEL_1203 yzxw, gbra
#define MATHS_SHIFT_LABEL_1210 yzyx, gbgr
#define MATHS_SHIFT_LABEL_1211 yzyy, gbgg
#define MATHS_SHIFT_LABEL_1212 yzyz, gbgb
#define MATHS_SHIFT_LABEL_1213 yzyw, gbga
#define MATHS_SHIFT_LABEL_1220 yzzx, gbbr
#define MATHS_SHIFT_LABEL_1221 yzzy, gbbg
#define MATHS_SHIFT_LABEL_1222 yzzz, gbbb
#define MATHS_SHIFT_LABEL_1223 yzzw, gbba
#define MATHS_SHIFT_LABEL_1230 yzwx, gbar
#define MATHS_SHIFT_LABEL_1231 yzwy, gbag
#define MATHS_SHIFT_LABEL_1232 yzwz, gbab
#define MATHS_SHIFT_LABEL_1233 yzww, gbaa
#define MATHS_SHIFT_LABEL_1300 ywxx, garr
#define MATHS_SHIFT_LABEL_1301 ywxy, garg
#define MATHS_SHIFT_LABEL_1302 ywxz, garb
#define MATHS_SHIFT_LABEL_1303 ywxw, gara
#define MATHS_SHIFT_LABEL_1310 ywyx, gagr
#define MATHS_SHIFT_LABEL_1311 ywyy, gagg
#define MATHS_SHIFT_LABEL_1312 ywyz, gagb
#define MATHS_SHIFT_LABEL_1313 ywyw, gaga
#define MATHS_SHIFT_LABEL_1320 ywzx, gabr
#define MATHS_SHIFT_LABEL_1321 ywzy, gabg
#define MATHS_SHIFT_LABEL_1322 ywzz, gabb
#define MATHS_SHIFT_LABEL_1323 ywzw, gaba
#define MATHS_SHIFT_LABEL_1330 ywwx, gaar
#define MATHS_SHIFT_LABEL_1331 ywwy, gaag
#define MATHS_SHIFT_LABEL_1332 ywwz, gaab
#define MATHS_SHIFT_LABEL_1333 ywww, gaaa
#define MATHS_SHIFT_LABEL_2000 zxxx, brrr
#define MATHS_SHIFT_LABEL_2001 zxxy, brrg
#define MATHS_SHIFT_LABEL_2002 zxxz, brrb
#define MATHS_SHIFT_LABEL_2003 zxxw, brra
#define MATHS_SHIFT_LABEL_2010 zxyx, brgr
#define MATHS_SHIFT_LABEL_2011 zxyy, brgg
#define MATHS_SHIFT_LABEL_2012 zxyz, brgb
#define MATHS_SHIFT_LABEL_2013 zxyw, brga
#define MATHS_SHIFT_LABEL_2020 zxzx, brbr
#define MATHS_SHIFT_LABEL_2021 zxzy, brbg
#define MATHS_SHIFT_LABEL_2022 zxzz, brbb
#define MATHS_SHIFT_LABEL_2023 zxzw, brba
#define MATHS_SHIFT_LABEL_2030 zxwx, brar
#define MATHS_SHIFT_LABEL_2031 zxwy, brag
#define MATHS_SHIFT_LABEL_2032 zxwz, brab
#define MATHS_SHIFT_LABEL_2033 zxww, braa
#define MATHS_SHIFT_LABEL_2100 zyxx, bgrr
#define MATHS_SHIFT_LABEL_2101 zyxy, bgrg
#define MATHS_SHIFT_LABEL_2102 zyxz, bgrb
#define MATHS_SHIFT_LABEL_2103 zyxw, bgra
#define MATHS_SHIFT_LABEL_2110 zyyx, bggr
#define MATHS_SHIFT_LABEL_2111 zyyy, bggg
#define MATHS_SHIFT_LABEL_2112 zyyz, bggb
#define MATHS_SHIFT_LABEL_2113 zyyw, bgga
#define MATHS_SHIFT_LABEL_2120 zyzx, bgbr
#define MATHS_SHIFT_LABEL_2121 zyzy, bgbg
#define MATHS_SHIFT_LABEL_2122 zyzz, bgbb
#define MATHS_SHIFT_LABEL_2123 zyzw, bgba
#define MATHS_SHIFT_LABEL_2130 zywx, bgar
#define MATHS_SHIFT_LABEL_2131 zywy, bgag
#define MATHS_SHIFT_LABEL_2132 zywz, bgab
#define MATHS_SHIFT_LABEL_2133 zyww, bgaa
#define MATHS_SHIFT_LABEL_2200 zzxx, bbrr
#define MATHS_SHIFT_LABEL_2201 zzxy, bbrg
#define MATHS_SHIFT_LABEL_2202 zzxz, bbrb
#define MATHS_SHIFT_LABEL_2203 zzxw, bbra
#define MATHS_SHIFT_LABEL_2210 zzyx, bbgr
#define MATHS_SHIFT_LABEL_2211 zzyy, bbgg
#define MATHS_SHIFT_LABEL_2212 zzyz, bbgb
#define MATHS_SHIFT_LABEL_2213 zzyw, bbga
#define MATHS_SHIFT_LABEL_2220 zzzx, bbbr
#define MATHS_SHIFT_LABEL_2221 zzzy, bbbg
#define MATHS_SHIFT_LABEL_2222 zzzz, bbbb
#define MATHS_SHIFT_LABEL_2223 zzzw, bbba
#define MATHS_SHIFT_LABEL_2230 zzwx, bbar
#define MATHS_SHIFT_LABEL_2231 zzwy, bbag
#define MATHS_SHIFT_LABEL_2232 zzwz, bbab
#define MATHS_SHIFT_LABEL_2233 zzww, bbaa
#define MATHS_SHIFT_LABEL_2300 zwxx, barr
#define MATHS_SHIFT_LABEL_2301 zwxy, barg
#define MATHS_SHIFT_LABEL_2302 zwxz, barb
#define MATHS_SHIFT_LABEL_2303 zwxw, bara
#define MATHS_SHIFT_LABEL_2310 zwyx, bagr
#define MATHS_SHIFT_LABEL_2311 zwyy, bagg
#define MATHS_SHIFT_LABEL_2312 zwyz, bagb
#define MATHS_SHIFT_LABEL_2313 zwyw, baga
#define MATHS_SHIFT_LABEL_2320 zwzx, babr
#define MATHS_SHIFT_LABEL_2321 zwzy, babg
#define MATHS_SHIFT_LABEL_2322 zwzz, babb
#define MATHS_SHIFT_LABEL_2323 zwzw, baba
#define MATHS_SHIFT_LABEL_2330 zwwx, baar
#define MATHS_SHIFT_LABEL_2331 zwwy, baag
#define MATHS_SHIFT_LABEL_2332 zwwz, baab
#define MATHS_SHIFT_LABEL_2333 zwww, baaa
#define MATHS_SHIFT_LABEL_3000 wxxx, arrr
#define MATHS_SHIFT_LABEL_3001 wxxy, arrg
#define MATHS_SHIFT_LABEL_3002 wxxz, arrb
#define MATHS_SHIFT_LABEL_3003 wxxw, arra
#define MATHS_SHIFT_LABEL_3010 wxyx, argr
#define MATHS_SHIFT_LABEL_3011 wxyy, argg
#define MATHS_SHIFT_LABEL_3012 wxyz, argb
#define MATHS_SHIFT_LABEL_3013 wxyw, arga
#define MATHS_SHIFT_LABEL_3020 wxzx, arbr
#define MATHS_SHIFT_LABEL_3021 wxzy, arbg
#define MATHS_SHIFT_LABEL_3022 wxzz, arbb
#define MATHS_SHIFT_LABEL_3023 wxzw, arba
#define MATHS_SHIFT_LABEL_3030 wxwx, arar
#define MATHS_SHIFT_LABEL_3031 wxwy, arag
#define MATHS_SHIFT_LABEL_3032 wxwz, arab
#define MATHS_SHIFT_LABEL_3033 wxww, araa
#define MATHS_SHIFT_LABEL_3100 wyxx, agrr
#define MATHS_SHIFT_LABEL_3101 wyxy, agrg
#define MATHS_SHIFT_LABEL_3102 wyxz, agrb
#define MATHS_SHIFT_LABEL_3103 wyxw, agra
#define MATHS_SHIFT_LABEL_3110 wyyx, aggr
#define MATHS_SHIFT_LABEL_3111 wyyy, aggg
#define MATHS_SHIFT_LABEL_3112 wyyz, aggb
#define MATHS_SHIFT_LABEL_3113 wyyw, agga
#define MATHS_SHIFT_LABEL_3120 wyzx, agbr
#define MATHS_SHIFT_LABEL_3121 wyzy, agbg
#define MATHS_SHIFT_LABEL_3122 wyzz, agbb
#define MATHS_SHIFT_LABEL_3123 wyzw, agba
#define MATHS_SHIFT_LABEL_3130 wywx, agar
#define MATHS_SHIFT_LABEL_3131 wywy, agag
#define MATHS_SHIFT_LABEL_3132 wywz, agab
#define MATHS_SHIFT_LABEL_3133 wyww, agaa
#define MATHS_SHIFT_LABEL_3200 wzxx, abrr
#define MATHS_SHIFT_LABEL_3201 wzxy, abrg
#define MATHS_SHIFT_LABEL_3202 wzxz, abrb
#define MATHS_SHIFT_LABEL_3203 wzxw, abra
#define MATHS_SHIFT_LABEL_3210 wzyx, abgr
#define MATHS_SHIFT_LABEL_3211 wzyy, abgg
#define MATHS_SHIFT_LABEL_3212 wzyz, abgb
#define MATHS_SHIFT_LABEL_3213 wzyw, abga
#define MATHS_SHIFT_LABEL_3220 wzzx, abbr
#define MATHS_SHIFT_LABEL_3221 wzzy, abbg
#define MATHS_SHIFT_LABEL_3222 wzzz, abbb
#define MATHS_SHIFT_LABEL_3223 wzzw, abba
#define MATHS_SHIFT_LABEL_3230 wzwx, abar
#define MATHS_SHIFT_LABEL_3231 wzwy, abag
#define MATHS_SHIFT_LABEL_3232 wzwz, abab
#define MATHS_SHIFT_LABEL_3233 wzww, abaa
#define MATHS_SHIFT_LABEL_3300 wwxx, aarr
#define MATHS_SHIFT_LABEL_3301 wwxy, aarg
#define MATHS_SHIFT_LABEL_3302 wwxz, aarb
#define MATHS_SHIFT_LABEL_3303 wwxw, aara
#define MATHS_SHIFT_LABEL_3310 wwyx, aagr
#define MATHS_SHIFT_LABEL_3311 wwyy, aagg
#define MATHS_SHIFT_LABEL_3312 wwyz, aagb
#define MATHS_SHIFT_LABEL_3313 wwyw, aaga
#define MATHS_SHIFT_LABEL_3320 wwzx, aabr
#define MATHS_SHIFT_LABEL_3321 wwzy, aabg
#define MATHS_SHIFT_LABEL_3322 wwzz, aabb
#define MATHS_SHIFT_LABEL_3323 wwzw, aaba
#define MATHS_SHIFT_LABEL_3330 wwwx, aaar
#define MATHS_SHIFT_LABEL_3331 wwwy, aaag
#define MATHS_SHIFT_LABEL_3332 wwwz, aaab
#define MATHS_SHIFT_LABEL_3333 wwww, aaaa

#define MATHS_SHIFT_GEN1_FIELD(A) MATHS_SHIFT_LABEL_##A
#define MATHS_SHIFT_GEN2_FIELD(A,B) MATHS_SHIFT_LABEL_##A##B
#define MATHS_SHIFT_GEN3_FIELD(A,B,C) MATHS_SHIFT_LABEL_##A##B##C
#define MATHS_SHIFT_GEN4_FIELD(A,B,C,D) MATHS_SHIFT_LABEL_##A##B##C##D