#pragma once

#include "primitives/core.h"
#include "primitives/matrix2x2.h"
#include "primitives/matrix2x3.h"
#include "primitives/matrix2x4.h"
#include "primitives/matrix3x2.h"
#include "primitives/matrix3x3.h"
#include "primitives/matrix3x4.h"
#include "primitives/matrix4x2.h"
#include "primitives/matrix4x3.h"
#include "primitives/matrix4x4.h"
#include "primitives/vector2.h"
#include "primitives/vector3.h"
#include "primitives/vector4.h"